spring:
  application:
    name: DiscoveryServer


server:
  port: 5005

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    fetch-registry: false
    register-with-eureka: false




