spring:
  application:
    name: gateway

debug: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

server:
  port: 5025

eureka:
  instance:
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:5005/eureka/