spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



server:
  port: 5025

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5005/eureka/


