spring:
  application:
    name: BookService

  datasource:
    url: jdbc:postgresql://localhost:2427/bookMicroservices
    username: postgres
    password: kevin.2427
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092  
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false

cloudinary:
  config:
    cloudName: dz36f7lni
    clientId: 827236279878875
    clientSecret: at0M7fDTwe8MBc6jtth5GFrcU2s

server:
  port: 5010
